version: '3.8'
services:
  onlineschool-db:
    image: postgres:15-alpine
    container_name: onlineschool-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: onlineschool
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
